spring:
  jackson:
    serialization:
      failOnEmptyBeans: false
  datasource:
    plataform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-225-237-84.compute-1.amazonaws.com:5432/dadlba8rt8eoru?useSSL=false
    username: ijwuesrkigcmja
    password: 2a6b8b359da230c0abdee31ecbd365cd4bdbf2051098c79188d7064ce2f22a1c
  h2:
    console:
      enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      temp:
        useJdbcMetadaDefaults: false
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        generateStatistics: true
        formatSql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
logging:
  level:
    org.hibernate.stat: debug
    org.hibernate.type: trace